firstDjango/books/urls.py
from django.urls import path
from .views import books_list, book_detail, add_book

app_name = 'books'

urlpatterns = [
    path('<int:book_id>', book_detail, name='details'),
    path('', books_list, name='list'),
    path('add', add_book, name='add')
]

firstDjango/firstDjango/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
    path('posts/', include('posts.urls')),
    path('', include('main.urls')),
    path('tags/', include('tags.urls')),
    path('', include('register.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('galleries/', include('galleries.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

firstDjango/main/urls.py
from django.urls import path
from .views import hello, some_test, about, contact, user_profile

app_name = 'main'

urlpatterns = [
    path('', hello, name='hello'),
    path('testy', some_test),
    path('about', about, name='about'),
    path('contact/', contact, name='contact'),
    path('user/<int:user_profile_id>/profile', user_profile, name='userprofile')
]

firstDjango/posts/urls.py
from django.urls import path
from .views import posts_list, post_details, add_post_form


app_name = 'posts'

urlpatterns = [
    path('', posts_list, name='list'),
    path('add/', add_post_form, name='add'),
    path('<int:post_id>', post_details, name='details'),
]

firstDjango/register/urls.py
from django.urls import path

from .views import register


app_name = 'register'
urlpatterns = [
    path('register/', register, name='register'),
]

firstDjango/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <title>{% block title %} {% endblock %}</title>
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">
    {% block styles %} {% endblock %}
</head>
<body>
        <div class="container">
        <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
          <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
            <span class="fs-4"> My books and posts !</span>
          </a>
          <ul class="nav nav-pills">
            <li class="nav-item">
                <a href="{% url 'main:hello' %}" class="nav-link"> Main page</a>
            </li>
              <li class="nav-item">
                  <a href="{% url 'posts:list' %}" class="nav-link"> List of posts</a>
              </li>
            <li class="nav-item">
                  <a href="{% url 'books:list' %}" class="nav-link"> List of Books</a>
              </li>
                      <div class="col-md-3 text-end">
                            {% if user.is_authenticated %}
                                <a type="button" class="btn btn-outline-primary me-2" href="{% url 'logout' %}">Logout</a>
                            {% else %}
                                <a type="button" class="btn btn-outline-primary me-2" href="{% url 'login' %}">Login</a>
                                <a type="button" class="btn btn-primary" href="{% url 'register:register' %}">Sign-up</a>
                            {% endif %}
                        </div>
          </ul>
        </header>
        </div>
    <nav>
        <ul>
        </ul>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <p class="col-md-4 mb-0 text-body-secondary">© 2023 Company, Inc</p>

    <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
    </a>
        <nav>
            <ul class="nav col-md-4 justify-content-end">
                <li class="nav-item">
                    <a href="{% url 'main:about' %}" class="nav-link px-2 text-body-secondary"> About </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'main:contact' %}" class="nav-link px-2 text-body-secondary"> Contact </a>
                </li>
            </ul>
        </nav>
    </footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
{% block additional_scripts %}{% endblock %}
</body>
</html>