firstDjango/books/urls.py
from django.urls import path
from .views import books_list, book_detail, add_book

app_name = 'books'

urlpatterns = [
    path('<int:book_id>', book_detail, name='details'),
    path('', books_list, name='list'),
    path('add', add_book, name='add')
]

firstDjango/firstDjango/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
    path('posts/', include('posts.urls')),
    path('', include('main.urls')),
    path('tags/', include('tags.urls')),
    path('', include('register.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('galleries/', include('galleries.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

firstDjango/main/urls.py
from django.urls import path
from .views import hello, some_test, about, contact, user_profile

app_name = 'main'

urlpatterns = [
    path('', hello, name='hello'),
    path('testy', some_test),
    path('about', about, name='about'),
    path('contact/', contact, name='contact'),
    path('user/<int:user_profile_id>/profile', user_profile, name='userprofile')
]

firstDjango/books/models.py
from django.db import models
from common.models import Timestamped


class Author(Timestamped):
    name = models.CharField(max_length=200)
    birth_day = models.IntegerField()
    death_year = models.IntegerField(blank=True, null=True)
    biogram = models.TextField()

    def __str__(self):
        return f'{self.name}  ({self.birth_day} - )'


class Book(Timestamped):
    title = models.CharField(max_length=200)
    description = models.TextField()
    publication_year = models.IntegerField()
    available = models.BooleanField(default=False)
    tags = models.ManyToManyField("tags.Tag", related_name="books")
    authors = models.ManyToManyField(Author, related_name="books")
    cover = models.ImageField(upload_to="books/covers/%Y/%m/%d", null=True, blank=True)

    def __str__(self):
        return f'{self.title} - {self.author}'

firstDjango/books/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from dal import autocomplete
from django import forms
from .models import Book
from tags.models import Tag


class BookForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=autocomplete.ModelSelect2Multiple(url='tags:tag-autocomplete')
    )

    class Meta:
        model = Book
        fields = '__all__'

        def __init__(self, *args, **kwargs):
            super().__init__(self, *args, **kwargs)
            self.helper = FormHelper
            self.helper.form_method = 'post'
            self.helper.form_action = 'book:add'
            self.helper.add_input(Submit('submit', 'wyślij'))

firstDjango/books/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import Book
from .forms import BookForm


def book_detail(request, book_id):
    book = Book.objects.get(pk=book_id)
    context = {'book': book}
    return render(request, 'books/book_detail.html', context)


def books_list(request):
    books = Book.objects.all()
    context = {'books_list': books}
    return render(request, 'books/list.html', context)


def add_book(request):
    form = BookForm()
    if request.method == "POST":
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse("books:add"))
    return render(
        request=request,
        template_name="books/add.html",
        context={"form": form}
    )

firstDjango/books/templates/books/add.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static %}

{%  block style %}
    <link href= "{% static 'books/css/style.css' %}" rel=stylesheet">
{% endblock %}

{% block header %}
    <p><h3>Dodawanie nowej książki:</h3></p>
{% endblock %}

{% block title %}
{% endblock %}

{% block content %}
{#    <form method = "POST">#}
    <form method = "POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
        <hr>
        {{ formset.management_form }}
        {% for form in formset %}
            <div class="author-form">
                {{ form|crispy }}
            </div>
        {% endfor %}
        <hr>
        <button id="add-form" type="button" class="btn btn-primary">Dodaj autora</button>
        <hr>
        <input type="submit" name="submit" value="Prześlij" class="btn btn-primary"/>
{#        <button type="submit"#}
{#        class = "btn btn-primary">Wyślij</button>#}
    </form>
{% endblock %}

{% block additional_scripts %}
    <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
    {{ form.media }}
    <script>
        let form = document.querySelectorAll(".photo-form")
        let container = document.querySelector("#form-container")
        let addButton = document.querySelector("#add-form")
        let totalForms = document.querySelector("#id_form-TOTAL_FORMS")
        let formNum = form.length - 1
        addButton.addEventListener('click', addForm)
        function addForm(e){
            e.preventDefault()
            let newForm = form[0].cloneNode(true)
            let formRegex = RegExp(`form-(\\d){1}-`,'g')
            formNum++
            newForm.innerHTML = newForm.innerHTML.replace(formRegex, `form-${formNum}-`)
            container.insertBefore(newForm, addButton)
            totalForms.setAttribute(`value`, `${formNum + 1}`)
        }
    </script>
{% endblock %}

firstDjango/books/templates/books/book_detail.html
{% extends 'base.html' %}
{% block content %}
    <h2>{{ book.title }}</h2>
    <div>
        <small>Autor : {{ book.author }} </small>
    </div>
    <div>
        <br><br>
        <p> {{ book.description }} </p>
    </div>
{% endblock %}

firstDjango/books/templates/books/list.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
<link href="{% static 'books/css/style.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <h1> List of books </h1>
    <ul class="list-group">
        {% for book in books_list %}
            <li class="list-group-item">
                <a href="{% url 'books:details' book.id %}"> {{ book.title }} </a>
                {% if book.available == True %}
                    (Dostępna !)
                {% else %}
                    (Niedostępna)
                {% endif %}
            </li>
        {% endfor %}
    </ul>
{% endblock %}