firstDjango/firstDjango/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
    path('posts/', include('posts.urls')),
    path('', include('main.urls')),
    path('tags/', include('tags.urls')),
    path('', include('register.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('galleries/', include('galleries.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

firstDjango/main/urls.py
from django.urls import path
from .views import hello, some_test, about, contact, user_profile

app_name = 'main'

urlpatterns = [
    path('', hello, name='hello'),
    path('testy', some_test),
    path('about', about, name='about'),
    path('contact/', contact, name='contact'),
    path('user/<int:user_profile_id>/profile', user_profile, name='userprofile')
]

firstDjango/posts/urls.py
from django.urls import path
from .views import posts_list, post_details, add_post_form


app_name = 'posts'

urlpatterns = [
    path('', posts_list, name='list'),
    path('add/', add_post_form, name='add'),
    path('<int:post_id>', post_details, name='details'),
]

firstDjango/posts/models.py
from django.db import models
from django.utils.timezone import now, timedelta


class CheckAgeMixin:
    def is_older_than(self, n=1):
        """Check if created is older than now() - n days """
        delta = timedelta(days=n)
        return now() - self.created > delta


class Timestamped(models.Model, CheckAgeMixin):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Post(Timestamped):
    title = models.CharField(verbose_name='Tytuł' ,max_length=250)
    content = models.TextField(verbose_name='Treść')
    published = models.BooleanField(verbose_name='Opublikowany', default=False)
    sponsored = models.BooleanField(verbose_name='Sponsorowany', default=False)
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE, related_name="posts")
    tags = models.ManyToManyField("tags.Tag", related_name="posts")
    categories = models.ManyToManyField(Category, related_name='posts', blank=True)
    example_file = models.FileField(upload_to='posts/examples/', blank=True, null=True)
    image = models.ImageField(upload_to="posts/images/%Y/%m/%d", null=True, blank=True)

    def __str__(self):
        return f'{self.id} {self.title}'

firstDjango/posts/forms.py
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, HTML
from crispy_forms.helper import FormHelper
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'published', 'sponsored', 'image']
        labels = {
            'title': 'Tytuł',
            'content': 'Treść',
            'published': 'Opublikowany',
            'sponsored': 'Sponsorowany'
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_action = 'post:add'
        self.helper.layout = Layout(
            Fieldset(
                'Dodaj post',
                'title',
                'content',
                'published',
                'sponsored',
                'image',
                'tags',
                'categories',
            ),
            ButtonHolder(
                Submit('submit', 'Dodaj', css_class='btn btn-primary'),
                css_class="d-flex justify-content-end"
            )
        )

firstDjango/posts/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.core.paginator import Paginator
from .models import Post
from .forms import PostForm


def post_details(request, post_id):
    post = Post.objects.get(pk=post_id)
    context = {'post': post}
    if post.published:
        context['post'] = post
    return render(request, 'posts/post_details.html', context)


def posts_list(request):
    posts = Post.objects.filter(published=True)
    q = request.GET.get("q")
    if q:
        posts = posts.filter(title__icontains=q)

    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    posts_list = paginator.get_page(page_number)
    context = {'posts_list': posts_list}
    return render(request, 'posts/list.html', context)


def add_post_form(request):
    if request.method == 'POST' and request.user.is_authenticated:
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            form.save_m2m()
            return HttpResponseRedirect(reverse("posts:add"))
    else:
        form = PostForm()
    return render(
        request,
        "posts/add.html",
        {'form': form}
    )


def edit_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()

    else:
        form = PostForm(instance=post)

    return render(request, "posts/add.html", {'form': form})

firstDjango/posts/templates/posts/add.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} POST {% endblock %}
{% block content %}
{% crispy form %}
{% endblock %}

firstDjango/posts/templates/posts/edit.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static %}

{%  block style %}
    <link href="{% static 'posts/css/style.css' %}" rel=stylesheet">
{% endblock %}

{% block header %}
    <p><h3>Edytowanie posta:</h3></p>
{% endblock %}

{% block title %}  Edytuj post: {% endblock %}

{% block content %}
    <form method = "POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit"
    class = "btn btn-primary">Wyślij</button>
    </form>
{% endblock %}

{% block additional_scripts %}
    <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
    {{ form.media }}
{% endblock %}

firstDjango/posts/templates/posts/list.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
<link href="{% static 'posts/css/style.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <h1> List of posts </h1>
    <ul class="list-group">
        {% for post in posts_list %}
            <li class="list-group-item">
                <a href="{% url 'posts:details' post.id %}"> {{ post.id }}. {{ post.title }} </a>
                {% if post.sponsored %}
                    (Post sponsorowany!)
                {% endif %}
            </li>
        {% endfor %}
    </ul>
<!--Pagination-->
<nav aria-label="Page navigation">
     <ul class="pagination justify-content-center">
         {% if posts_list.has_previous %}
         <li class="page-item">
            <a class="page-link" href="?page={{ posts_list.previous_page_number }}">Previous</a>
         </li>
         {% else %}
         <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Previous</a>
         </li>
             {% endif %}
             {% for i in posts_list.paginator.page_range %}
             {% if posts_list.number == i %}
         <li class="page-item active" aria-current="page">
         <span class="page-link">
             {{ i }}
             <span class="sr-only">(current)</span>
         </span>
         </li>
             {% else %}
             <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
             {% endif %}
             {% endfor %}
             {% if posts_list.has_next %}
             <li class="page-item">
             <a class="page-link" href="?page={{ posts_list.next_page_number }}">Next</a>
         </li>
             {% else %}
             <li class="page-item disabled">
             <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Next</a>
         </li>
         {% endif %}
    </ul>
</nav>
<!--end of Pagination-->

{% endblock %}

firstDjango/posts/templates/posts/post_details.html
{% extends 'base.html' %}
{% block content %}
    <h2>{{ post.title }}</h2>
    <div>
        <p> {{ post.content }} </p>
    </div>
    {% if post.example_file %}
        <div> Download <a href="{{ post.example_file.url }}">Example</a> </div>
    {% endif %}
    <div>
        {% if post.image %}
            <img src="{{ post.image.url }} " >
    </div>
    {% endif %}
{% endblock %}